FROM python:latest

WORKDIR /home/dash-cron

COPY . ./

RUN apt-get update
RUN apt-get -y install cron

ADD crontab /etc/cron.d/hello-cron

RUN chmod 0644 /etc/cron.d/hello-cron

RUN touch /var/log/cron.log

RUN apt-get install build-essential libsvm-dev ffmpeg libsm6 libxext6 -y

RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x run_s3.sh

CMD ["cron", "-f"]