FROM python:3.7.3-slim
WORKDIR /home/dash

COPY . ./

RUN apt-get update
RUN apt-get -y install cron

RUN chmod +x boot.sh

RUN apt-get --allow-releaseinfo-change update && apt-get upgrade && apt-get install build-essential libsvm-dev ffmpeg libsm6 libxext6 -y

RUN pip3 install -r /requirements.txt

ENTRYPOINT ["./boot.sh"]


