FROM python:3.7.3-slim

WORKDIR /home/dash-cron

COPY . ./

ADD crontab /etc/cron.d/hello-cron

RUN chmod 0644 /etc/cron.d/hello-cron

RUN touch /var/log/cron.log

RUN apt-get update
RUN apt-get -y install cron

RUN apt-get update && apt-get upgrade && apt-get install build-essential libsvm-dev ffmpeg libsm6 libxext6 -y

RUN pip3 install -r /requirements.txt

RUN chmod +x /run_s3.sh

CMD ["cron", "-f"]