FROM python:latest
WORKDIR /home/dash

COPY . ./

RUN chmod +x boot.sh

RUN apt-get update && apt-get install build-essential libsvm-dev ffmpeg libsm6 libxext6 -y

RUN pip3 install -r /requirements.txt

ENTRYPOINT ["./boot.sh"]


